### ISSUE TITLE
Crashing when changing username via /nick, leaving room, and rejoining.

### ISSUE THREAD

**Issue by Magicfulness** [AxeBane/The-Scribe#21]
I was able to consistently crash the bot when I was testing it whenever I changed nicknames using /nick, left the room, and rejoined it. I did this because the bot no longer responded to my commands after /nick.  I had an urge to test on the actual bot but I didn't want to actually crash it lol. Seems to be that the bot is trying to delete a user that isn't in the user list in the first place. I think checking if user is null ought to fix it, but I'm not that familiar with bots. Error log is below if you're interested in debugging this, if not ignore it.

TypeError: Cannot read property 'id' of undefined
    at Room.onLeave (~/PSstuff/The-Scribe/rooms.js:69:24)
    at Object.message (~/PSstuff/The-Scribe/parser.js:459:20)
    at Object.splitMessage (~/PSstuff/The-Scribe/parser.js:201:9)
    at Object.data (~/PSstuff/The-Scribe/parser.js:174:10)
    at WebSocketConnection.<anonymous> (~/PSstuff/The-Scribe/main.js:236:10)
    at emitOne (events.js:96:13)
    at WebSocketConnection.emit (events.js:188:7)
    at WebSocketConnection.processFrame (~/PSstuff/The-Scribe/node_modules/websocket/lib/WebSocketConnection.js:536:26)
    at ~/PSstuff/The-Scribe/node_modules/websocket/lib/WebSocketConnection.js:310:40
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
~@linux-swgj:~/PSstuff/The-Scribe> node main.js

**Comment by sirDonovan** [comment]
I can't seem to reproduce this. Have you changed any code in rooms.js or parser.js?

**Comment by Magicfulness** [comment]
I haven't touched either, this was during my changes to commands.js for the typo stuff. I did see if checking if user is undefined and returning null if it is would stop crashes, and it seemed to. But yeah I don't understand bots well enough to know exactly why.
